#n=10 a 10 years
data<-read.csv('year_bytes - n=10 a 10y.csv')
data$year = 10 * floor(data$year/10)
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+9)
data$bytes = (data$bytes-min(data$bytes))/(max(data$bytes)-min(data$bytes))
bpt<-boxplot(data$bytes~data$year,main="size of file", ylab="bytes", xlab="time")
lines(1:10,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('complete_score - n=10 a 10y.csv')
data$year = 10 * floor(data$year/10)
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+9)
data$ent_pc = (data$ent_pc-min(data$ent_pc))/(max(data$ent_pc)-min(data$ent_pc))
bpt<-boxplot(data$ent_pc~data$year,main="pitch class entropy complete score", ylab="pitch class entropy", xlab="time")
lines(1:10,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('16m - n=10 a 10y.csv')
data$year = 10 * floor(data$year/10)
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+9)
data$ent_pc = (data$ent_pc-min(data$ent_pc))/(max(data$ent_pc)-min(data$ent_pc))
bpt<-boxplot(data$ent_pc~data$year,main="pitch class entropy 16 measures", ylab="pitch class entropy", xlab="time")
lines(1:10,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('complete_score - n=10 a 10y.csv',nrows=248)
data$year = 10 * floor(data$year/10)
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+9)
data$ent_pi = (data$ent_pi-min(data$ent_pi))/(max(data$ent_pi)-min(data$ent_pi))
bpt<-boxplot(data$ent_pi~data$year,main="pitch interval entropy complete score", ylab="pitch interval entropy", xlab="time")
lines(1:10,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('16m - n=10 a 10y.csv')
data$year = 10 * floor(data$year/10)
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+9)
data$ent_pi = (data$ent_pi-min(data$ent_pi))/(max(data$ent_pi)-min(data$ent_pi))
bpt<-boxplot(data$ent_pi~data$year,main="pitch interval entropy 16 measures", ylab="pitch interval entropy", xlab="time")
lines(1:10,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('complete_score - n=10 a 10y.csv',nrows=248)
data$year = 10 * floor(data$year/10)
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+9)
data$ent_ioi = (data$ent_ioi-min(data$ent_ioi))/(max(data$ent_ioi)-min(data$ent_ioi))
bpt<-boxplot(data$ent_ioi~data$year,main="inter-onset interval (IOI) entropy complete score", ylab="inter-onset interval entropy", xlab="time")
lines(1:10,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('16m - n=10 a 10y.csv',nrows=248)
data$year = 10 * floor(data$year/10)
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+9)
data$ent_ioi = (data$ent_ioi-min(data$ent_ioi))/(max(data$ent_ioi)-min(data$ent_ioi))
bpt<-boxplot(data$ent_ioi~data$year,main="inter-onset interval (IOI) entropy 16 measures", ylab="inter-onset interval entropy", xlab="time")
lines(1:10,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('complete_score - n=10 a 10y.csv')
data$year = 10 * floor(data$year/10)
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+9)
data$pc = (data$pc-min(data$pc))/(max(data$pc)-min(data$pc))
data$pi = (data$pi-min(data$pi))/(max(data$pi)-min(data$pi))
data$pioi = (data$pioi-min(data$pioi))/(max(data$pioi)-min(data$pioi))
all_compl = (data$pc+data$pi+data$pioi)
norm_all_compl = (all_compl-min(all_compl))/(max(all_compl)-min(all_compl))
bpt<-boxplot(norm_all_compl~data$year,main="overall non-weigthed entropy complete score", ylab="overall entropy", xlab="time")
lines(1:10,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('16m - n=10 a 10y.csv')
data$year = 10 * floor(data$year/10)
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+9)
data$pc = (data$pc-min(data$pc))/(max(data$pc)-min(data$pc))
data$pi = (data$pi-min(data$pi))/(max(data$pi)-min(data$pi))
data$pioi = (data$pioi-min(data$pioi))/(max(data$pioi)-min(data$pioi))
all_compl = (data$pc+data$pi+data$pioi)
norm_all_compl = (all_compl-min(all_compl))/(max(all_compl)-min(all_compl))
bpt<-boxplot(norm_all_compl~data$year,main="overall non-weigthed entropy 16 measures", ylab="overall entropy", xlab="time")
lines(1:10,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('complete_score - n=10 a 10y.csv')
data$year = 10 * floor(data$year/10)
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+9)
data$tc = (-data$tc-min(-data$tc))/(max(-data$tc)-min(-data$tc))
bpt<-boxplot(data$tc~data$year, main="negative tonal certainty complete score", ylab="negative tonal certainty", xlab="time")
lines(1:10,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('16m - n=10 a 10y.csv')
data$year = 10 * floor(data$year/10)
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+9)
data$tc = (-data$tc-min(-data$tc))/(max(-data$tc)-min(-data$tc))
bpt<-boxplot(data$tc~data$year, main="negative tonal certainty 16 measures", ylab="negative tonal certainty", xlab="time")
lines(1:10,bpt$stats[3,],col="blue",lwd=3)

#n=20 a 50 years
#Kompression unterschiedlich großer Dateien -> schlechte Vergleichbarkeit
data<-read.csv('year_bytes - n=20 a 50y.csv',nrows=81)
data$year = ifelse(as.numeric(substr(data$year, 3, 4))>50, paste0(substr(data$year, 1, 2),50), paste0(substr(data$year, 1, 2),"00"))
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+49)
data$bytes = (data$bytes-min(data$bytes))/(max(data$bytes)-min(data$bytes))
bpt<-boxplot(data$bytes~data$year,main="size of file", ylab="bytes", xlab="time")
lines(1:5,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('complete_score - n=20 a 50y.csv',nrows=248)
data$year = ifelse(as.numeric(substr(data$year, 3, 4))>50, paste0(substr(data$year, 1, 2),50), paste0(substr(data$year, 1, 2),"00"))
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+49)
data$ent_pc = (data$ent_pc-min(data$ent_pc))/(max(data$ent_pc)-min(data$ent_pc))
bpt<-boxplot(data$ent_pc~data$year,main="pitch class entropy complete score", ylab="pitch class entropy", xlab="time")
lines(1:5,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('16m - n=20 a 50y.csv',nrows=248)
data$year = ifelse(as.numeric(substr(data$year, 3, 4))>50, paste0(substr(data$year, 1, 2),50), paste0(substr(data$year, 1, 2),"00"))
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+49)
data$ent_pc = (data$ent_pc-min(data$ent_pc))/(max(data$ent_pc)-min(data$ent_pc))
bpt<-boxplot(data$ent_pc~data$year,main="pitch class entropy 16 measures", ylab="pitch class entropy", xlab="time")
lines(1:5,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('complete_score - n=20 a 50y.csv',nrows=248)
data$year = ifelse(as.numeric(substr(data$year, 3, 4))>50, paste0(substr(data$year, 1, 2),50), paste0(substr(data$year, 1, 2),"00"))
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+49)
data$ent_pi = (data$ent_pi-min(data$ent_pi))/(max(data$ent_pi)-min(data$ent_pi))
bpt<-boxplot(data$ent_pi~data$year,main="pitch interval entropy complete score", ylab="pitch interval entropy", xlab="time")
lines(1:5,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('16m - n=20 a 50y.csv',nrows=248)
data$year = ifelse(as.numeric(substr(data$year, 3, 4))>50, paste0(substr(data$year, 1, 2),50), paste0(substr(data$year, 1, 2),"00"))
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+49)
data$ent_pi = (data$ent_pi-min(data$ent_pi))/(max(data$ent_pi)-min(data$ent_pi))
bpt<-boxplot(data$ent_pi~data$year,main="pitch interval entropy 16 measures", ylab="pitch interval entropy", xlab="time")
lines(1:5,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('complete_score - n=20 a 50y.csv',nrows=248)
data$year = ifelse(as.numeric(substr(data$year, 3, 4))>50, paste0(substr(data$year, 1, 2),50), paste0(substr(data$year, 1, 2),"00"))
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+49)
data$ent_ioi = (data$ent_ioi-min(data$ent_ioi))/(max(data$ent_ioi)-min(data$ent_ioi))
bpt<-boxplot(data$ent_ioi~data$year,main="inter-onset interval (IOI) entropy complete score", ylab="inter-onset interval entropy", xlab="time")
lines(1:5,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('16m - n=20 a 50y.csv',nrows=248)
data$year = ifelse(as.numeric(substr(data$year, 3, 4))>50, paste0(substr(data$year, 1, 2),50), paste0(substr(data$year, 1, 2),"00"))
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+49)
data$ent_ioi = (data$ent_ioi-min(data$ent_ioi))/(max(data$ent_ioi)-min(data$ent_ioi))
bpt<-boxplot(data$ent_ioi~data$year,main="inter-onset interval (IOI) entropy 16 measures", ylab="inter-onset interval entropy", xlab="time")
lines(1:5,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('complete_score - n=20 a 50y.csv',nrows=248)
data$year = ifelse(as.numeric(substr(data$year, 3, 4))>50, paste0(substr(data$year, 1, 2),50), paste0(substr(data$year, 1, 2),"00"))
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+49)
data$ent_pc = (data$ent_pc-min(data$ent_pc))/(max(data$ent_pc)-min(data$ent_pc))
data$ent_pi = (data$ent_pi-min(data$ent_pi))/(max(data$ent_pi)-min(data$ent_pi))
data$ent_ioi = (data$ent_ioi-min(data$ent_ioi))/(max(data$ent_ioi)-min(data$ent_ioi))
all_compl = (data$ent_pc+data$ent_pi+data$ent_ioi)
norm_all_compl = (all_compl-min(all_compl))/(max(all_compl)-min(all_compl))
bpt<-boxplot(norm_all_compl~data$year,main="overall non-weigthed entropy complete score", ylab="overall entropy", xlab="time")
lines(1:5,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('16m - n=20 a 50y.csv',nrows=248)
data$year = ifelse(as.numeric(substr(data$year, 3, 4))>50, paste0(substr(data$year, 1, 2),50), paste0(substr(data$year, 1, 2),"00"))
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+49)
data$ent_pc = (data$ent_pc-min(data$ent_pc))/(max(data$ent_pc)-min(data$ent_pc))
data$ent_pi = (data$ent_pi-min(data$ent_pi))/(max(data$ent_pi)-min(data$ent_pi))
data$ent_ioi = (data$ent_ioi-min(data$ent_ioi))/(max(data$ent_ioi)-min(data$ent_ioi))
all_compl = (data$ent_pc+data$ent_pi+data$ent_ioi)
norm_all_compl = (all_compl-min(all_compl))/(max(all_compl)-min(all_compl))
bpt<-boxplot(norm_all_compl~data$year,main="overall non-weigthed entropy 16 measures", ylab="overall entropy", xlab="time")
lines(1:5,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('complete_score - n=20 a 50y.csv',nrows=248)
data$year = ifelse(as.numeric(substr(data$year, 3, 4))>50, paste0(substr(data$year, 1, 2),50), paste0(substr(data$year, 1, 2),"00"))
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+49)
data$tc = (-data$tc-min(-data$tc))/(max(-data$tc)-min(-data$tc))
bpt<-boxplot(data$tc~data$year, main="negative tonal certainty complete score", ylab="negative tonal certainty", xlab="time")
lines(1:5,bpt$stats[3,],col="blue",lwd=3)

data<-read.csv('16m - n=20 a 50y.csv')
data$year = ifelse(as.numeric(substr(data$year, 3, 4))>50, paste0(substr(data$year, 1, 2),50), paste0(substr(data$year, 1, 2),"00"))
data$year = paste0(paste0(data$year,"-"),as.numeric(data$year)+49)
data$tc = (-data$tc-min(-data$tc))/(max(-data$tc)-min(-data$tc))
bpt<-boxplot(data$tc~data$year, main="negative tonal certainty 16 measures", ylab="negative tonal certainty", xlab="time")
lines(1:5,bpt$stats[3,],col="blue",lwd=3)

#1720s
data<-read.csv('year_bytes_20s.csv')
data$bytes = (data$bytes-min(data$bytes))/(max(data$bytes)-min(data$bytes))
bpt<-boxplot(data$bytes, main="size of file", ylab="bytes")

data<-read.csv('1720s - complete.csv')
data$ent_pc = (data$ent_pc-min(data$ent_pc))/(max(data$ent_pc)-min(data$ent_pc))
bpt<-boxplot(data$ent_pc, main="pitch class entropy complete score", ylab="pitch class entropy")

data<-read.csv('1720s - 16m.csv')
data$ent_pc = (data$ent_pc-min(data$ent_pc))/(max(data$ent_pc)-min(data$ent_pc))
bpt<-boxplot(data$ent_pc, main="pitch class entropy 16 measures", ylab="pitch class entropy")

data<-read.csv('1720s - complete.csv')
data$ent_pi = (data$ent_pi-min(data$ent_pi))/(max(data$ent_pi)-min(data$ent_pi))
bpt<-boxplot(data$ent_pi, main="pitch interval entropy complete score", ylab="pitch interval entropy")

data<-read.csv('1720s - 16m.csv')
data$ent_pi = (data$ent_pi-min(data$ent_pi))/(max(data$ent_pi)-min(data$ent_pi))
bpt<-boxplot(data$ent_pi, main="pitch interval entropy 16 measures", ylab="pitch interval entropy")

data<-read.csv('1720s - complete.csv')
data$ent_ioi = (data$ent_ioi-min(data$ent_ioi))/(max(data$ent_ioi)-min(data$ent_ioi))
bpt<-boxplot(data$ent_ioi, main="inter-onset interval (IOI) entropy complete score", ylab="pitch interval entropy")

data<-read.csv('1720s - 16m.csv')
data$ent_ioi = (data$ent_ioi-min(data$ent_ioi))/(max(data$ent_ioi)-min(data$ent_ioi))
bpt<-boxplot(data$ent_ioi, main="inter-onset interval (IOI) entropy 16 measures", ylab="pitch interval entropy")

data<-read.csv('1720s - complete.csv')
data$ent_pc = (data$ent_pc-min(data$ent_pc))/(max(data$ent_pc)-min(data$ent_pc))
data$ent_pi = (data$ent_pi-min(data$ent_pi))/(max(data$ent_pi)-min(data$ent_pi))
data$ent_ioi = (data$ent_ioi-min(data$ent_ioi))/(max(data$ent_ioi)-min(data$ent_ioi))
all_compl = (data$ent_pc+data$ent_pi+data$ent_ioi)
norm_all_compl = (all_compl-min(all_compl))/(max(all_compl)-min(all_compl))
bpt<-boxplot(norm_all_compl,main="overall non-weigthed entropy complete score", ylab="overall entropy")

data<-read.csv('1720s - 16m.csv')
data$ent_pc = (data$ent_pc-min(data$ent_pc))/(max(data$ent_pc)-min(data$ent_pc))
data$ent_pi = (data$ent_pi-min(data$ent_pi))/(max(data$ent_pi)-min(data$ent_pi))
data$ent_ioi = (data$ent_ioi-min(data$ent_ioi))/(max(data$ent_ioi)-min(data$ent_ioi))
all_compl = (data$ent_pc+data$ent_pi+data$ent_ioi)
norm_all_compl = (all_compl-min(all_compl))/(max(all_compl)-min(all_compl))
bpt<-boxplot(norm_all_compl,main="overall non-weigthed entropy 16 measures", ylab="overall entropy")

data<-read.csv('1720s - complete.csv')
data$tc = (-data$tc-min(-data$tc))/(max(-data$tc)-min(-data$tc))
bpt<-boxplot(data$tc, main="negative tonal certainty complete score", ylab="negative tonal certainty")

data<-read.csv('1720s - 16m.csv')
data$tc = (-data$tc-min(-data$tc))/(max(-data$tc)-min(-data$tc))
bpt<-boxplot(data$tc, main="negative tonal certainty 16 measures", ylab="negative tonal certainty")
